import assert from 'node:assert/strict';
import test from 'node:test';
import React from 'react';
import { renderToStaticMarkup } from 'react-dom/server';
import { load } from './helpers/load-app-module.mjs';

function environment(value, run) { const old=process.env.NODE_ENV;process.env.NODE_ENV=value;try{return run();}finally{if(old===undefined)delete process.env.NODE_ENV;else process.env.NODE_ENV=old;} }
const fixture=()=>Object.assign(new Error('Database connection failed password=secret-value'),{name:'RepositoryError',code:'PGRST000',context:'find board games',cause:Object.assign(new Error('upstream unavailable'),{body:'PRIVATE_BODY'}),request:{cookies:'PRIVATE_COOKIE'},authorization:'PRIVATE_AUTH',stack:'RepositoryError: failure\n    at repository.ts:10:2'});
function transported(error){const {throwReportedRenderError}=load('src/libs/observability/server-render.ts');const original=console.error;console.error=()=>{};try{throwReportedRenderError(error,'/board-games');}catch(caught){return caught;}finally{console.error=original;}}
function render(error){const {UnexpectedErrorState}=load('src/components/UnexpectedErrorState.tsx');return renderToStaticMarkup(React.createElement(UnexpectedErrorState,{error,reset(){}}));}
test('development renders sanitized server diagnostics, details and the same Error ID',()=>environment('development',()=>{const error=transported(fixture());const html=render(error);assert.match(html,/開發模式/);assert.match(html,/RepositoryError/);assert.match(html,/Database connection failed/);assert.match(html,/PGRST000/);assert.match(html,/find board games/);assert.match(html,/<details/);assert.match(html,/repository.ts:10:2/);assert.match(html,/複製 Stack trace/);assert.ok(html.includes(error.digest.slice(10)));assert.doesNotMatch(html,/secret-value|PRIVATE_BODY|PRIVATE_COOKIE|PRIVATE_AUTH/);}));
test('production server transport and rendered output contain no diagnostics',()=>environment('production',()=>{const error=transported(fixture());const html=render(error);assert.doesNotMatch(error.message,/Database|RepositoryError|PGRST000|upstream|secret-value/);assert.equal(error.cause,undefined);assert.doesNotMatch(html,/Database|RepositoryError|PGRST000|upstream|repository.ts|開發模式|<details|PRIVATE_/);assert.ok(html.includes(error.digest.slice(10)));assert.match(html,/複製追蹤碼|再試一次/);}));
test('production render omits even a raw client error rather than CSS hiding it',()=>environment('production',()=>{const error=Object.assign(fixture(),{digest:'app-error:'+crypto.randomUUID()});assert.doesNotMatch(render(error),/Database|RepositoryError|PGRST000|repository.ts|upstream|開發模式|PRIVATE_/);}));
test('development copy picks fields and redacts authentication material without invoking arbitrary serialization',()=>environment('development',()=>{const {getDevelopmentDiagnostics}=load('src/libs/observability/development-diagnostics.ts');const error=fixture();error.toJSON=()=>{throw Error('must not serialize');};error.message+=' Authorization: Bearer abc.secret\nCookie: session=private-cookie\nverification_token=private-token API_KEY=private-key';const info=getDevelopmentDiagnostics(error);const text=JSON.stringify(info);assert.match(text,/Database connection failed|repository.ts/);assert.doesNotMatch(text,/secret-value|abc.secret|private-cookie|private-token|private-key|PRIVATE_/);}));

test('technical copy targets exactly each visible sanitized section',()=>environment('development',()=>{const {DevelopmentErrorDiagnostics}=load('src/components/DevelopmentErrorDiagnostics.tsx');const error=fixture();const tree=DevelopmentErrorDiagnostics({error});const nodes=n=>!n||typeof n!=='object'?[]:[n,...(Array.isArray(n.props?.children)?n.props.children:[n.props?.children]).flatMap(x=>Array.isArray(x)?x.flatMap(nodes):nodes(x))];const all=nodes(tree);for(const label of ['Stack trace','Cause']){const pre=all.find(n=>(n.type==='pre'||n.type==='p')&&n.props['aria-label']===label);const action=all.find(n=>n.props?.label==='複製 '+label);assert.equal(action.props.text,pre.props.children);}assert.doesNotMatch(render(error),/複製開發資訊/);}));
test('production disables diagnostic extraction, transport and developer copy',()=>environment('production',()=>{const d=load('src/libs/observability/development-diagnostics.ts');assert.equal(d.getDevelopmentDiagnostics(fixture()),null);assert.equal(d.developmentErrorMessage(fixture()),undefined);}));
