import assert from 'node:assert/strict';
import test from 'node:test';
import React from 'react';
import {renderToStaticMarkup} from 'react-dom/server';
import {readFileSync} from 'node:fs';
import {load} from './helpers/load-app-module.mjs';
function render(error,mode='development'){const before=process.env.NODE_ENV;process.env.NODE_ENV=mode;try {const {UnexpectedErrorState}=load('src/components/UnexpectedErrorState.tsx');return renderToStaticMarkup(React.createElement(UnexpectedErrorState,{error:Object.assign(error,{digest:'app-error:'+crypto.randomUUID()}),reset(){}}));}finally{if(before===undefined)delete process.env.NODE_ENV;else process.env.NODE_ENV=before;}}
test('diagnostic message is a prominent heading with secondary error type',()=>{const html=render(new ReferenceError('Buttn is not defined'));assert.match(html,/<h3[^>]*text-xl[^>]*>Buttn is not defined<\/h3>/);assert.match(html,/<p[^>]*text-xs[^>]*>ReferenceError<\/p>/);assert.doesNotMatch(html,/類型：|訊息：/);assert.doesNotMatch(html,/支援資訊/);assert.match(html,/複製錯誤訊息/);});
test('details are native, collapsed and distinguish available technical sections',()=>{const html=render(Object.assign(new Error('failure'),{cause:new Error('cause only')}));assert.match(html,/<details[^>]*>/);assert.doesNotMatch(html,/<details[^>]*\sopen/);assert.match(html,/查看技術細節/);assert.match(html,/Stack trace/);assert.match(html,/Cause/);assert.match(html,/max-h-72[^"]*overflow-auto/);assert.doesNotMatch(html,/>Code<|>Context</);});
test('copy purposes are distinct and production still omits diagnostic output',()=>{const html=render(new Error('PRIVATE_DEBUG_MESSAGE'));assert.doesNotMatch(html,/複製開發資訊/);assert.match(html,/複製 Stack trace/);assert.match(html,/複製追蹤碼/);assert.doesNotMatch(html,/僅含追蹤碼與記錄時間/);const production=render(new Error('PRIVATE_DEBUG_MESSAGE'),'production');assert.doesNotMatch(production,/PRIVATE_DEBUG_MESSAGE|Stack trace|開發模式|<details/);assert.match(production,/錯誤追蹤碼|複製追蹤碼|再試一次/);});
test('error shells own growth without modifying normal website shells',()=>{const global=readFileSync('src/app/global-error.tsx','utf8');assert.match(global,/h-auto/);assert.match(global,/shrink-0/);assert.doesNotMatch(global,/items-center justify-center/);for(const group of ['admin','public','auth','authenticated'])assert.match(readFileSync('src/app/('+group+')/error.tsx','utf8'),/shrink-0/);});

test('reference is inline selectable code without header-body block chrome',()=>{const {ErrorReference}=load('src/components/ErrorReference.tsx');const id=crypto.randomUUID();const html=renderToStaticMarkup(React.createElement(ErrorReference,{errorId:id}));assert.match(html,/<code/);assert.ok(html.includes(id));assert.match(html,/aria-label="複製追蹤碼"/);assert.match(html,/lucide-copy/);assert.doesNotMatch(html,/<pre|border-b|網站名稱/);});
