import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import test from "node:test";

const readProjectFile = (path) => readFile(new URL(`../${path}`, import.meta.url), "utf8");

test("identity row types use PostgREST number IDs while UUID identities remain separate", async () => {
  const types = await readProjectFile("src/types/database.tsx");

  for (const typeName of [
    "UserProfileId",
    "BoardGameBorrowingId",
    "EventAttendanceId",
    "AnnouncementId",
  ]) {
    assert.match(types, new RegExp(`export type ${typeName} = number;`));
  }

  assert.match(types, /export type User = \{\s*id: UUID;/);
  assert.match(types, /export type BoardGameBorrowing = \{\s*id: BoardGameBorrowingId;/);
  assert.match(types, /export type EventAttendance = \{\s*id: EventAttendanceId;/);
  assert.match(types, /export type UserProfile = \{\s*id: UserProfileId;\s*user_id: UUID;/);
});

test("identity route parameters are parsed once before numeric repository contracts", async () => {
  const parser = await readProjectFile("src/libs/zod/ids.ts");
  const borrowingRoute = await readProjectFile("src/app/api/admin/borrowings/[id]/route.ts");
  const attendanceRoute = await readProjectFile(
    "src/app/api/admin/events/[id]/attendances/[attendanceId]/route.ts",
  );
  const borrowingRepository = await readProjectFile(
    "src/repositories/board-game-borrowings.repository.ts",
  );
  const attendanceRepository = await readProjectFile(
    "src/repositories/event-attendances.repository.ts",
  );

  assert.match(parser, /regex\(\/\^\\d\+\$\//);
  assert.match(parser, /Number\.isSafeInteger\(value\) && value > 0/);
  assert.match(borrowingRoute, /parsePositiveIntegerId\(rawId\)/);
  assert.match(attendanceRoute, /parsePositiveIntegerId\(rawAttendanceId\)/);
  assert.match(borrowingRepository, /findById: async \(id: BoardGameBorrowingId\)/);
  assert.match(attendanceRepository, /findById: async \(id: EventAttendanceId\)/);
});

test("canonical schema remains a current remote snapshot with deployed self-check-in only", async () => {
  const schema = await readProjectFile("supabase/schema/canonical-public-schema.sql");

  assert.match(schema, /Semantics: this is the current deployed remote baseline/);
  assert.match(schema, /check_in_opens_at timestamptz/);
  assert.match(schema, /check_in_closes_at timestamptz/);
  assert.match(schema, /constraint events_check_in_window_check check/);
  assert.match(schema, /constraint event_attendances_event_id_user_id_key unique \(event_id, user_id\)/);
  assert.match(schema, /id bigint generated by default as identity constraint user_profiles_pkey primary key/);
  assert.match(schema, /id bigint generated by default as identity constraint board_game_borrowings_pkey primary key/);
  assert.match(schema, /id bigint generated by default as identity constraint event_attendances_pkey primary key/);
  assert.doesNotMatch(schema, /checkout_borrowing/);
  assert.doesNotMatch(schema, /return_borrowing/);
  assert.doesNotMatch(schema, /set_current_academic_year/);
  assert.doesNotMatch(schema, /register_user\(\s*p_email text,[\s\S]*p_real_name text/);
});
