import { NextResponse } from "next/server";
import { ZodError, z } from "zod";
import { getCurrentUser, isAdminByUserId } from "@/libs/auth";
import { boardGamesService } from "@/services/board-games/board-games.service";
import { boardGameMasterDataSchema } from "@/services/board-games/board-games.schema";
import { BoardGameLocationInUseError, BoardGameLocationNotFoundError, DuplicateBoardGameLocationNameError } from "@/services/board-games/board-games.errors";
import { unexpectedErrorResponse } from "@/libs/api/server-response";
type Context = { params: Promise<{ id: string }> }; async function authorized() { const user = await getCurrentUser(); return Boolean(user && await isAdminByUserId(user.id)); }
export async function PATCH(request: Request, { params }: Context) { if (!await authorized()) return NextResponse.json({ message: "您沒有管理桌遊位置的權限" }, { status: 403 }); try { return NextResponse.json({ data: await boardGamesService.updateLocation((await params).id, boardGameMasterDataSchema.parse(await request.json())) }); } catch (error) { if (error instanceof ZodError) return NextResponse.json({ message: "輸入資料格式不正確", errors: z.treeifyError(error) }, { status: 400 }); if (error instanceof BoardGameLocationNotFoundError) return NextResponse.json({ message: error.message }, { status: 404 }); if (error instanceof DuplicateBoardGameLocationNameError) return NextResponse.json({ message: error.message }, { status: 409 }); return unexpectedErrorResponse("[PATCH /api/admin/board-game-locations/[id]]", error, "更新桌遊位置失敗，請稍後再試"); } }
export async function DELETE(_: Request, { params }: Context) { if (!await authorized()) return NextResponse.json({ message: "您沒有管理桌遊位置的權限" }, { status: 403 }); try { await boardGamesService.deleteLocation((await params).id); return NextResponse.json({ data: null }); } catch (error) { if (error instanceof BoardGameLocationNotFoundError) return NextResponse.json({ message: error.message }, { status: 404 }); if (error instanceof BoardGameLocationInUseError) return NextResponse.json({ message: error.message }, { status: 409 }); return unexpectedErrorResponse("[DELETE /api/admin/board-game-locations/[id]]", error, "刪除桌遊位置失敗，請稍後再試"); } }
