import { NextResponse } from "next/server";
import { ZodError, z } from "zod";
import { getCurrentUser, isAdminByUserId } from "@/libs/auth";
import { AcademicYearInUseError, AcademicYearNotFoundError, academicYearsService, DuplicateAcademicYearError } from "@/services/academic-years/academic-years.service";
type Context = { params: Promise<{ id: string }> };
async function authorized() { const user = await getCurrentUser(); return Boolean(user && await isAdminByUserId(user.id)); }
function errorResponse(error: unknown) { if (error instanceof ZodError) return NextResponse.json({ message: "輸入資料格式不正確", errors: z.treeifyError(error) }, { status: 400 }); if (error instanceof AcademicYearNotFoundError) return NextResponse.json({ message: error.message }, { status: 404 }); if (error instanceof DuplicateAcademicYearError || error instanceof AcademicYearInUseError) return NextResponse.json({ message: error.message }, { status: 409 }); return NextResponse.json({ message: "學年度操作失敗" }, { status: 500 }); }
export async function PATCH(request: Request, { params }: Context) { if (!await authorized()) return NextResponse.json({ message: "您沒有管理學年度的權限" }, { status: 403 }); try { const { id } = await params; const body = await request.json(); const data = body.action === "set-current" ? await academicYearsService.setCurrent(id) : await academicYearsService.update(id, body); return NextResponse.json({ data }); } catch (error) { console.error("[PATCH /api/admin/academic-years/[id]]", error); return errorResponse(error); } }
export async function DELETE(_: Request, { params }: Context) { if (!await authorized()) return NextResponse.json({ message: "您沒有管理學年度的權限" }, { status: 403 }); try { await academicYearsService.delete((await params).id); return NextResponse.json({ data: null }); } catch (error) { return errorResponse(error); } }
