export const SUPABASE_URL = process.env.SUPABASE_URL!;
export const SUPABASE_SERVICE_ROLE_KEY = process.env.SUPABASE_SERVICE_ROLE_KEY!;
export const NEXT_PUBLIC_TURNSTILE_SITE_KEY =
  process.env.NEXT_PUBLIC_TURNSTILE_SITE_KEY!;
export const TURNSTILE_SECRET_KEY = process.env.TURNSTILE_SECRET_KEY!;
export const REGISTER_KEY_SECRET = process.env.REGISTER_KEY_SECRET;
