-- NTUST Board Game Club canonical public schema snapshot.
--
-- Source: verified current remote metadata and Phase 1F deployment catalog.
-- Purpose: readable handover reference and a schema-only starting point for a
-- brand-new Supabase database. This is NOT a migration and must not be applied
-- to an existing environment.
-- Semantics: remote baseline through 202609010006, plus the explicitly marked
-- Phase 3E 公告欄位（202609130001）已於 2026-09-14 遠端套用並唯讀驗證。
-- Phase 3E-B 桌遊／活動欄位（202609130002）已於同日遠端套用並驗證。
-- Other tables remain the historical reference, not a complete deployment inventory.
--
-- This snapshot intentionally contains no data, seed records, credentials,
-- sessions, secrets, or application migration-history assumptions.

-- pgcrypto is required by gen_random_uuid() and generate_membership_register_keys().
create schema if not exists extensions;
create extension if not exists pgcrypto with schema extensions;

-- Remote extension inventory also contained uuid-ossp, pg_stat_statements,
-- supabase_vault, and the built-in plpgsql language. They are not referenced by
-- the public application objects below. Enable platform-managed extensions in
-- the target Supabase project only when that environment requires them.

create type public.attendance_status as enum ('present', 'absent', 'late');
create type public.board_game_status as enum (
  'available',
  'borrowed',
  'maintenance',
  'lost',
  'damaged',
  'retired'
);
create type public.borrowing_status as enum (
  'pending',
  'approved',
  'rejected',
  'borrowed',
  'returned',
  'cancelled'
);
create type public.membership_register_key_status as enum (
  'available',
  'claimed',
  'revoked',
  'expired'
);

-- These names match the verified remote schema. Do not correct the spelling in
-- a snapshot or migration without a separately approved compatibility plan.
create type public.merbership_status as enum (
  'pending',
  'active',
  'expired',
  'suspended',
  'cancelled'
);
create type public.merbership_type as enum ('annual', 'lifetime');

create table public.users (
  id uuid constraint users_pkey primary key default gen_random_uuid(),
  created_at timestamptz not null default now(),
  name text not null,
  email text not null,
  email_verified_at timestamptz,
  avatar text,
  updated_at timestamptz not null default now(),
  constraint users_email_key unique (email)
);

create table public.email_verification_tokens (
  id uuid constraint email_verification_tokens_pkey primary key default gen_random_uuid(),
  user_id uuid not null
    references public.users (id)
    on delete cascade,
  token_hash text not null,
  expires_at timestamptz not null,
  consumed_at timestamptz,
  created_at timestamptz not null default now(),
  constraint email_verification_tokens_token_hash_key unique (token_hash),
  constraint email_verification_tokens_expiry_check check (expires_at > created_at)
);

create index email_verification_tokens_user_created_idx
  on public.email_verification_tokens (user_id, created_at desc);

create table public.academic_years (
  id uuid constraint academic_years_pkey primary key default gen_random_uuid(),
  start_date date not null,
  end_date date not null,
  year text not null,
  is_current boolean not null,
  constraint academic_years_year_key unique (year),
  constraint academic_years_date_range_check check (start_date < end_date)
);

create table public.board_game_categories (
  id uuid constraint board_game_category_pkey primary key default gen_random_uuid(),
  name text not null,
  description text
);

create table public.board_game_locations (
  id uuid constraint locations_pkey primary key default gen_random_uuid(),
  name text not null,
  description text
);

create table public.events (
  id uuid constraint events_pkey primary key default gen_random_uuid(),
  created_at timestamptz not null default now(),
  start_time timestamptz not null,
  end_time timestamptz not null,
  name text not null,
  description text,
  -- Phase 3E-B：202609130002 已於 2026-09-14 遠端套用。
  description_format text not null default 'plain_text',
  rich_description jsonb,
  constraint events_description_format_check check (description_format in ('plain_text', 'rich_text_v1')),
  constraint events_rich_description_check check (
    (description_format = 'plain_text' and rich_description is null)
    or (description_format = 'rich_text_v1' and rich_description is not null
      and jsonb_typeof(rich_description) = 'object'
      and coalesce(rich_description ->> 'type', '') = 'doc')
  ),
  check_in_opens_at timestamptz,
  check_in_closes_at timestamptz,
  constraint events_check_in_window_check check (
    (check_in_opens_at is null and check_in_closes_at is null)
    or (
      check_in_opens_at is not null
      and check_in_closes_at is not null
      and check_in_opens_at <= check_in_closes_at
    )
  )
);

create table public.user_profiles (
  id bigint generated by default as identity constraint user_profiles_pkey primary key,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  grade text,
  phone text not null,
  school text,
  department text,
  real_name text not null,
  user_id uuid not null,
  student_id text,
  constraint user_profiles_real_name_nonempty_check
    check (btrim(real_name) <> ''),
  constraint user_profiles_user_id_fkey
    foreign key (user_id) references public.users(id)
    on delete no action on update no action,
  constraint user_profiles_user_id_key unique (user_id)
);

create table public.auth_credentials (
  id uuid constraint auth_credentials_pkey primary key default gen_random_uuid(),
  created_at timestamptz not null default now(),
  password_hash text not null,
  updated_at timestamptz not null default now(),
  user_id uuid not null,
  constraint auth_credentials_user_id_fkey
    foreign key (user_id) references public.users(id)
    on delete no action on update no action
);

create table public.sessions (
  id uuid constraint seessions_pkey primary key default gen_random_uuid(),
  created_at timestamptz not null default now(),
  token text not null,
  expires_at timestamptz not null,
  last_accessed_at timestamptz not null default now(),
  user_id uuid not null,
  constraint seessions_token_key unique (token),
  constraint sessions_user_id_fkey
    foreign key (user_id) references public.users(id)
    on delete no action on update no action
);

create table public.officer_positions (
  id uuid constraint positions_pkey primary key default gen_random_uuid(),
  title text not null,
  created_at timestamptz not null default now(),
  academic_year_id uuid not null,
  user_id uuid not null,
  constraint officer_positions_academic_year_id_fkey
    foreign key (academic_year_id) references public.academic_years(id)
    on delete no action on update no action,
  constraint officer_positions_user_id_fkey
    foreign key (user_id) references public.users(id)
    on delete no action on update no action
);

create table public.board_games (
  id uuid constraint board_games_pkey primary key default gen_random_uuid(),
  created_at timestamptz not null default now(),
  name text not null,
  description text,
  -- Phase 3E-B：202609130002 已於 2026-09-14 遠端套用。
  description_format text not null default 'plain_text',
  rich_description jsonb,
  constraint board_games_description_format_check check (description_format in ('plain_text', 'rich_text_v1')),
  constraint board_games_rich_description_check check (
    (description_format = 'plain_text' and rich_description is null)
    or (description_format = 'rich_text_v1' and rich_description is not null
      and jsonb_typeof(rich_description) = 'object'
      and coalesce(rich_description ->> 'type', '') = 'doc')
  ),
  image text,
  updated_at timestamptz not null default now(),
  category_id uuid not null default gen_random_uuid(),
  location_id uuid not null default gen_random_uuid(),
  status public.board_game_status not null,
  inventory_number bigint not null,
  constraint board_games_category_id_fkey
    foreign key (category_id) references public.board_game_categories(id)
    on delete no action on update no action,
  constraint board_games_location_id_fkey
    foreign key (location_id) references public.board_game_locations(id)
    on delete no action on update no action,
  constraint board_games_inventory_number_key unique (inventory_number)
);

create table public.memberships (
  id uuid constraint merberships_pkey primary key default gen_random_uuid(),
  created_at timestamptz not null default now(),
  type public.merbership_type not null,
  status public.merbership_status not null,
  updated_at timestamptz not null default now(),
  joined_at timestamptz not null,
  academic_year_id uuid not null,
  user_id uuid not null,
  membership_register_key_id uuid,
  constraint merberships_academic_year_id_fkey
    foreign key (academic_year_id) references public.academic_years(id)
    on delete no action on update no action,
  constraint merberships_user_id_fkey
    foreign key (user_id) references public.users(id)
    on delete no action on update no action
);

create table public.membership_register_keys (
  id uuid constraint membership_register_keys_pkey primary key default gen_random_uuid(),
  academic_year_id uuid not null,
  sequence_number integer not null,
  register_key text not null,
  status public.membership_register_key_status not null default 'available',
  created_by_user_id uuid,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  claimed_at timestamptz,
  revoked_at timestamptz,
  constraint membership_register_keys_academic_year_id_fkey
    foreign key (academic_year_id) references public.academic_years(id)
    on delete restrict on update no action,
  constraint membership_register_keys_created_by_user_id_fkey
    foreign key (created_by_user_id) references public.users(id)
    on delete set null on update no action,
  constraint membership_register_keys_register_key_key unique (register_key),
  constraint membership_register_keys_year_sequence_key
    unique (academic_year_id, sequence_number),
  constraint membership_register_keys_sequence_number_check
    check (sequence_number > 0),
  constraint membership_register_keys_status_timestamps_check check (
    (status = 'claimed' and claimed_at is not null and revoked_at is null)
    or (status = 'revoked' and revoked_at is not null and claimed_at is null)
    or (status in ('available', 'expired') and claimed_at is null and revoked_at is null)
  )
);

alter table public.memberships
  add constraint memberships_membership_register_key_id_fkey
  foreign key (membership_register_key_id)
  references public.membership_register_keys(id)
  on delete set null on update no action;

create table public.board_game_borrowings (
  id bigint generated by default as identity constraint board_game_borrowings_pkey primary key,
  created_at timestamptz not null default now(),
  approved_at timestamptz,
  rejected_at timestamptz,
  cancelled_at timestamptz,
  borrowed_at timestamptz,
  due_at timestamptz,
  returned_at timestamptz,
  status public.borrowing_status not null,
  approved_by_user_id uuid,
  user_id uuid not null,
  board_game_id uuid not null,
  constraint board_game_borrowings_approved_by_user_id_fkey
    foreign key (approved_by_user_id) references public.users(id)
    on delete no action on update no action,
  constraint board_game_borrowings_user_id_fkey
    foreign key (user_id) references public.users(id)
    on delete no action on update no action,
  constraint board_game_borrowings_board_game_id_fkey
    foreign key (board_game_id) references public.board_games(id)
    on delete no action on update no action
);

create table public.board_game_reviews (
  id uuid constraint board_game_reviews_pkey primary key default gen_random_uuid(),
  board_game_id uuid not null,
  user_id uuid not null,
  rating smallint not null,
  content text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint board_game_reviews_board_game_id_fkey
    foreign key (board_game_id) references public.board_games(id)
    on delete no action on update no action,
  constraint board_game_reviews_user_id_fkey
    foreign key (user_id) references public.users(id)
    on delete no action on update no action,
  constraint board_game_reviews_user_game_key unique (board_game_id, user_id),
  constraint board_game_reviews_rating_check check (rating between 1 and 5),
  constraint board_game_reviews_content_check check (
    content is null or (btrim(content) <> '' and char_length(content) <= 2000)
  )
);

create index board_game_reviews_board_created_idx
  on public.board_game_reviews (board_game_id, created_at desc, id desc);

create view public.board_game_review_statistics
with (security_invoker = true)
as
select
  review.board_game_id,
  avg(review.rating)::numeric as average_rating,
  count(*)::bigint as rating_count,
  count(*) filter (where review.content is not null)::bigint as review_count
from public.board_game_reviews as review
group by review.board_game_id;

create view public.board_games_with_statistics
with (security_invoker = true)
as
select
  board_game.id,
  board_game.created_at,
  board_game.name,
  board_game.description,
  board_game.image,
  board_game.updated_at,
  board_game.category_id,
  board_game.location_id,
  board_game.status,
  board_game.inventory_number,
  coalesce(borrowing.completed_borrow_count, 0)::bigint
    as completed_borrow_count,
  review.average_rating,
  coalesce(review.rating_count, 0)::bigint as rating_count,
  coalesce(review.review_count, 0)::bigint as review_count
from public.board_games as board_game
left join (
  select
    borrowing.board_game_id,
    count(*)::bigint as completed_borrow_count
  from public.board_game_borrowings as borrowing
  where borrowing.status in ('borrowed', 'returned')
  group by borrowing.board_game_id
) as borrowing
  on borrowing.board_game_id = board_game.id
left join public.board_game_review_statistics as review
  on review.board_game_id = board_game.id;

-- Phase 3J-D：固定飽和參數讓分數不受目前目錄最大值或篩選結果影響。
create view public.board_game_popularity_statistics
with (security_invoker = true)
as
with
borrowing_statistics as (
  select borrowing.board_game_id, count(*)::bigint as completed_borrow_count
  from public.board_game_borrowings as borrowing
  where borrowing.status in ('borrowed', 'returned')
  group by borrowing.board_game_id
),
rating_totals as (
  select (coalesce(sum(review.rating), 0)::numeric + 20::numeric * 3.5::numeric)
    / (count(*)::numeric + 20::numeric) as community_mean
  from public.board_game_reviews as review
),
signals as (
  select board_game.id as board_game_id, board_game.name, board_game.description,
    board_game.image, board_game.status, board_game.inventory_number,
    board_game.category_id, board_game.location_id,
    coalesce(borrowing.completed_borrow_count, 0)::bigint as completed_borrow_count,
    review.average_rating, coalesce(review.rating_count, 0)::bigint as rating_count,
    coalesce(review.review_count, 0)::bigint as review_count, totals.community_mean
  from public.board_games as board_game
  left join borrowing_statistics as borrowing on borrowing.board_game_id = board_game.id
  left join public.board_game_review_statistics as review on review.board_game_id = board_game.id
  cross join rating_totals as totals
),
components as (
  select signals.*,
    least(1::double precision, greatest(0::double precision,
      ln(1::double precision + completed_borrow_count::double precision) / ln(21::double precision))) as borrowing_heat,
    least(1::double precision, greatest(0::double precision,
      ln(1::double precision + rating_count::double precision) / ln(11::double precision))) as rating_participation,
    case when rating_count = 0 then null::numeric else
      (rating_count::numeric * average_rating + 5::numeric * community_mean) / (rating_count::numeric + 5::numeric)
    end as bayesian_rating
  from signals
),
scored as (
  select components.*,
    case when rating_count = 0 then 0::double precision else
      least(1::double precision, greatest(0::double precision,
        ((bayesian_rating - 1::numeric) / 4::numeric)::double precision))
    end as rating_quality
  from components
)
select board_game_id, name, description, image, status, inventory_number,
  category_id, location_id, completed_borrow_count, average_rating, rating_count,
  review_count,
  0.50::double precision * borrowing_heat
    + 0.35::double precision * rating_quality
    + 0.15::double precision * rating_participation as popularity_score,
  bayesian_rating
from scored;

create table public.event_attendances (
  id bigint generated by default as identity constraint event_attendances_pkey primary key,
  attended_at timestamptz,
  status public.attendance_status not null,
  user_id uuid not null,
  event_id uuid not null,
  constraint event_attendances_user_id_fkey
    foreign key (user_id) references public.users(id)
    on delete no action on update no action,
  constraint event_attendances_event_id_fkey
    foreign key (event_id) references public.events(id)
    on delete no action on update no action,
  constraint event_attendances_event_id_user_id_key unique (event_id, user_id)
);

create table public.announcements (
  id bigint generated by default as identity constraint announcements_pkey primary key,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  title text not null,
  content text not null,
  -- Phase 3E：202609130001 已於 2026-09-14 遠端套用，支援 rich editor。
  content_format text not null default 'plain_text',
  rich_content jsonb,
  constraint announcements_content_format_check check (content_format in ('plain_text', 'rich_text_v1')),
  constraint announcements_rich_content_check check (
    (content_format = 'plain_text' and rich_content is null)
    or (content_format = 'rich_text_v1' and rich_content is not null
      and jsonb_typeof(rich_content) = 'object' and coalesce(rich_content ->> 'type', '') = 'doc')
  ),
  is_published boolean not null,
  published_at timestamptz,
  author_id uuid not null,
  constraint announcements_author_id_fkey
    foreign key (author_id) references public.users(id)
    on delete no action on update no action
);

create index membership_register_keys_created_by_user_id_idx
  on public.membership_register_keys (created_by_user_id)
  where created_by_user_id is not null;

create index membership_register_keys_year_status_created_idx
  on public.membership_register_keys (academic_year_id, status, created_at desc);

create unique index academic_years_one_current_year_idx
  on public.academic_years (is_current)
  where is_current = true;

create unique index board_game_borrowings_one_active_game_idx
  on public.board_game_borrowings (board_game_id)
  where status in ('approved', 'borrowed');

create unique index board_game_borrowings_one_open_user_game_idx
  on public.board_game_borrowings (user_id, board_game_id)
  where status in ('pending', 'approved', 'borrowed');

create index board_game_borrowings_completed_board_game_idx
  on public.board_game_borrowings (board_game_id)
  where status in ('borrowed', 'returned');

create unique index memberships_one_open_per_user_year_idx
  on public.memberships (user_id, academic_year_id)
  where status in ('pending', 'active', 'suspended');

create unique index memberships_register_key_id_unique_idx
  on public.memberships (membership_register_key_id)
  where membership_register_key_id is not null;

create or replace function public.register_user(
  p_email text,
  p_name text,
  p_password_hash text,
  p_real_name text,
  p_phone text
)
returns public.users
language plpgsql
security definer
set search_path = ''
as $$
declare
  new_user public.users;
begin
  insert into public.users (email, name)
  values (p_email, p_name)
  returning * into new_user;

  insert into public.auth_credentials (user_id, password_hash)
  values (new_user.id, p_password_hash);

  insert into public.user_profiles (user_id, real_name, phone)
  values (new_user.id, p_real_name, p_phone);

  return new_user;
end;
$$;

create or replace function public.issue_email_verification_token(
  p_user_id uuid,
  p_token_hash text,
  p_expires_at timestamptz,
  p_cooldown_before timestamptz
)
returns text
language plpgsql
security definer
set search_path = ''
as $$
declare
  target_verified_at timestamptz;
  latest_active_created_at timestamptz;
begin
  select email_verified_at into target_verified_at
  from public.users where id = p_user_id for update;
  if not found then
    raise foreign_key_violation using message = 'Email verification user does not exist';
  end if;
  if target_verified_at is not null then return 'already_verified'; end if;

  select created_at into latest_active_created_at
  from public.email_verification_tokens
  where user_id = p_user_id and consumed_at is null and expires_at > now()
  order by created_at desc limit 1;
  if latest_active_created_at is not null
    and latest_active_created_at > p_cooldown_before then
    return 'cooldown';
  end if;

  update public.email_verification_tokens set consumed_at = now()
  where user_id = p_user_id and consumed_at is null;
  insert into public.email_verification_tokens (user_id, token_hash, expires_at)
  values (p_user_id, p_token_hash, p_expires_at);
  return 'issued';
end;
$$;

create or replace function public.consume_email_verification_token(p_token_hash text)
returns text
language plpgsql
security definer
set search_path = ''
as $$
declare
  target_token public.email_verification_tokens;
  target_verified_at timestamptz;
begin
  select * into target_token
  from public.email_verification_tokens
  where token_hash = p_token_hash for update;
  if not found or target_token.consumed_at is not null
    or target_token.expires_at <= now() then return 'invalid'; end if;

  select email_verified_at into target_verified_at
  from public.users where id = target_token.user_id for update;
  if not found or target_verified_at is not null then
    update public.email_verification_tokens set consumed_at = now()
    where id = target_token.id;
    return 'invalid';
  end if;

  update public.users set email_verified_at = now()
  where id = target_token.user_id;
  update public.email_verification_tokens set consumed_at = now()
  where id = target_token.id;
  return 'verified';
end;
$$;

create or replace function public.update_updated_at_column()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create or replace function public.generate_membership_register_keys(
  p_academic_year_id uuid,
  p_count integer,
  p_secret text,
  p_created_by_user_id uuid
)
returns setof public.membership_register_keys
language plpgsql
security definer
set search_path = public, extensions
as $$
declare
  v_academic_year public.academic_years%rowtype;
  v_start_sequence integer;
  v_sequence integer;
  v_register_key text;
  v_digest text;
  v_row public.membership_register_keys%rowtype;
begin
  if p_count < 1 or p_count > 100 then
    raise exception 'INVALID_COUNT';
  end if;

  if p_secret is null or length(trim(p_secret)) < 16 then
    raise exception 'REGISTER_KEY_SECRET_NOT_CONFIGURED';
  end if;

  select * into v_academic_year
  from public.academic_years
  where id = p_academic_year_id;

  if not found then
    raise exception 'ACADEMIC_YEAR_NOT_FOUND';
  end if;

  perform pg_advisory_xact_lock(
    hashtext('membership_register_keys:' || p_academic_year_id::text)
  );

  select coalesce(max(sequence_number), 0) + 1 into v_start_sequence
  from public.membership_register_keys
  where academic_year_id = p_academic_year_id;

  for v_sequence in v_start_sequence..(v_start_sequence + p_count - 1) loop
    v_digest := upper(
      substring(
        encode(
          hmac(
            v_academic_year.year || 'NTUSTBGC' || lpad(v_sequence::text, 3, '0'),
            p_secret,
            'sha256'::text
          ),
          'hex'
        ) from 1 for 8
      )
    );
    v_register_key := v_academic_year.year || 'NTUSTBGC'
      || lpad(v_sequence::text, 3, '0') || v_digest;

    insert into public.membership_register_keys (
      academic_year_id,
      sequence_number,
      register_key,
      status,
      created_by_user_id
    ) values (
      p_academic_year_id,
      v_sequence,
      v_register_key,
      'available',
      p_created_by_user_id
    ) returning * into v_row;

    return next v_row;
  end loop;
end;
$$;

create or replace function public.claim_membership_register_key(
  p_register_key text,
  p_user_id uuid
)
returns table (
  result text,
  id uuid,
  user_id uuid,
  type text,
  academic_year_id uuid,
  status text,
  created_at timestamptz,
  updated_at timestamptz,
  joined_at timestamptz,
  membership_register_key_id uuid
)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_key public.membership_register_keys%rowtype;
  v_now timestamptz := now();
  v_membership public.memberships%rowtype;
begin
  select * into v_key
  from public.membership_register_keys
  where register_key = upper(trim(p_register_key))
  for update;

  if not found then
    result := 'not_found';
    return next;
    return;
  end if;

  if not exists (
    select 1
    from public.academic_years
    where id = v_key.academic_year_id and is_current = true
  ) then
    result := 'not_current_year';
    return next;
    return;
  end if;

  if v_key.status <> 'available' then
    result := 'unavailable';
    return next;
    return;
  end if;

  if exists (
    select 1
    from public.memberships
    where user_id = p_user_id
      and type = 'lifetime'
      and status in ('pending', 'active', 'suspended')
  ) then
    result := 'already_lifetime_member';
    return next;
    return;
  end if;

  if exists (
    select 1
    from public.memberships
    where user_id = p_user_id
      and academic_year_id = v_key.academic_year_id
      and type = 'annual'
      and status in ('pending', 'active', 'suspended')
  ) then
    result := 'already_current_member';
    return next;
    return;
  end if;

  begin
    insert into public.memberships (
      user_id,
      type,
      academic_year_id,
      status,
      joined_at,
      membership_register_key_id
    ) values (
      p_user_id,
      'annual',
      v_key.academic_year_id,
      'active',
      v_now,
      v_key.id
    ) returning * into v_membership;

    update public.membership_register_keys
    set status = 'claimed', claimed_at = v_now
    where id = v_key.id;
  exception
    when unique_violation then
      result := 'already_current_member';
      return next;
      return;
  end;

  result := 'claimed';
  id := v_membership.id;
  user_id := v_membership.user_id;
  type := v_membership.type;
  academic_year_id := v_membership.academic_year_id;
  status := v_membership.status;
  created_at := v_membership.created_at;
  updated_at := v_membership.updated_at;
  joined_at := v_membership.joined_at;
  membership_register_key_id := v_membership.membership_register_key_id;
  return next;
end;
$$;

-- Final deployed RPC definitions (Phase 1A–1D). These definitions supersede
-- the legacy declarations above and are retained here so this snapshot has the
-- same resulting behavior as the verified remote database.
create or replace function public.generate_membership_register_keys(
  p_academic_year_id uuid,
  p_count integer,
  p_secret text,
  p_created_by_user_id uuid
)
returns setof public.membership_register_keys
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_academic_year public.academic_years%rowtype;
  v_start_sequence integer;
  v_sequence integer;
  v_register_key text;
  v_digest text;
  v_row public.membership_register_keys%rowtype;
begin
  if p_count < 1 or p_count > 100 then raise exception 'INVALID_COUNT'; end if;
  if p_secret is null or length(trim(p_secret)) < 16 then raise exception 'REGISTER_KEY_SECRET_NOT_CONFIGURED'; end if;
  select * into v_academic_year from public.academic_years where id = p_academic_year_id;
  if not found then raise exception 'ACADEMIC_YEAR_NOT_FOUND'; end if;
  perform pg_catalog.pg_advisory_xact_lock(pg_catalog.hashtext('membership_register_keys:' || p_academic_year_id::text));
  select coalesce(max(sequence_number), 0) + 1 into v_start_sequence from public.membership_register_keys where academic_year_id = p_academic_year_id;
  for v_sequence in v_start_sequence..(v_start_sequence + p_count - 1) loop
    v_digest := upper(substring(encode(extensions.hmac(v_academic_year.year || 'NTUSTBGC' || lpad(v_sequence::text, 3, '0'), p_secret, 'sha256'::text), 'hex') from 1 for 8));
    v_register_key := v_academic_year.year || 'NTUSTBGC' || lpad(v_sequence::text, 3, '0') || v_digest;
    insert into public.membership_register_keys (academic_year_id, sequence_number, register_key, status, created_by_user_id)
    values (p_academic_year_id, v_sequence, v_register_key, 'available'::public.membership_register_key_status, p_created_by_user_id)
    returning * into v_row;
    return next v_row;
  end loop;
end;
$$;

create or replace function public.claim_membership_register_key(p_register_key text, p_user_id uuid)
returns table (result text, id uuid, user_id uuid, type text, academic_year_id uuid, status text, created_at timestamptz, updated_at timestamptz, joined_at timestamptz, membership_register_key_id uuid)
language plpgsql security definer set search_path = ''
as $$
declare
  v_key public.membership_register_keys%rowtype;
  v_now timestamptz := now();
  v_membership public.memberships%rowtype;
  v_type public.merbership_type;
begin
  select * into v_key from public.membership_register_keys as membership_register_key where membership_register_key.register_key = upper(trim(p_register_key)) for update;
  if not found then result := 'not_found'; return next; return; end if;
  perform pg_catalog.pg_advisory_xact_lock(pg_catalog.hashtext('membership_officer:' || p_user_id::text));
  if not exists (select 1 from public.academic_years as academic_year where academic_year.id = v_key.academic_year_id and academic_year.is_current = true) then result := 'not_current_year'; return next; return; end if;
  if v_key.status <> 'available'::public.membership_register_key_status then result := 'unavailable'; return next; return; end if;
  if exists (select 1 from public.memberships as membership where membership.user_id = p_user_id and membership.academic_year_id = v_key.academic_year_id and membership.status in ('pending'::public.merbership_status, 'active'::public.merbership_status, 'suspended'::public.merbership_status)) then result := 'already_current_member'; return next; return; end if;
  select case when exists (
    select 1 from public.officer_positions as officer
    join public.academic_years as officer_year on officer_year.id = officer.academic_year_id
    join public.academic_years as membership_year on membership_year.id = v_key.academic_year_id
    where officer.user_id = p_user_id and officer_year.start_date <= membership_year.start_date
  ) then 'lifetime'::public.merbership_type else 'annual'::public.merbership_type end into v_type;
  begin
    insert into public.memberships (user_id, type, academic_year_id, status, joined_at, membership_register_key_id)
    values (p_user_id, v_type, v_key.academic_year_id, 'active'::public.merbership_status, v_now, v_key.id)
    returning * into v_membership;
    update public.membership_register_keys as membership_register_key set status = 'claimed'::public.membership_register_key_status, claimed_at = v_now where membership_register_key.id = v_key.id;
  exception when unique_violation then result := 'already_current_member'; return next; return;
  end;
  result := 'claimed'; id := v_membership.id; user_id := v_membership.user_id; type := v_membership.type; academic_year_id := v_membership.academic_year_id; status := v_membership.status; created_at := v_membership.created_at; updated_at := v_membership.updated_at; joined_at := v_membership.joined_at; membership_register_key_id := v_membership.membership_register_key_id;
  return next;
end;
$$;

create function public.checkout_borrowing(p_borrowing_id bigint, p_due_at timestamptz)
returns public.board_game_borrowings language plpgsql security definer set search_path = ''
as $$
declare v_borrowing public.board_game_borrowings%rowtype; v_board_game public.board_games%rowtype;
begin
  select * into v_borrowing from public.board_game_borrowings where id = p_borrowing_id for update;
  if not found then raise exception using errcode = 'P0001', message = 'BORROWING_NOT_FOUND'; end if;
  if v_borrowing.status <> 'approved'::public.borrowing_status then raise exception using errcode = 'P0001', message = 'BORROWING_NOT_APPROVED'; end if;
  if p_due_at is null or p_due_at <= now() then raise exception using errcode = 'P0001', message = 'BORROWING_DUE_DATE_INVALID'; end if;
  select * into v_board_game from public.board_games where id = v_borrowing.board_game_id for update;
  if not found then raise exception using errcode = 'P0001', message = 'BOARD_GAME_NOT_FOUND'; end if;
  if v_board_game.status <> 'available'::public.board_game_status then raise exception using errcode = 'P0001', message = 'BOARD_GAME_NOT_AVAILABLE'; end if;
  update public.board_game_borrowings set status = 'borrowed'::public.borrowing_status, borrowed_at = now(), due_at = p_due_at where id = v_borrowing.id returning * into v_borrowing;
  update public.board_games set status = 'borrowed'::public.board_game_status where id = v_board_game.id;
  return v_borrowing;
end;
$$;

create function public.approve_borrowing(p_borrowing_id bigint, p_approver_user_id uuid)
returns public.board_game_borrowings language plpgsql security definer set search_path = '' as $$
declare v_borrowing public.board_game_borrowings%rowtype;
begin
  update public.board_game_borrowings set status='approved', approved_at=now(), approved_by_user_id=p_approver_user_id
  where id=p_borrowing_id and status='pending' returning * into v_borrowing;
  return v_borrowing;
end;
$$;

create function public.reject_borrowing(p_borrowing_id bigint, p_approver_user_id uuid)
returns public.board_game_borrowings language plpgsql security definer set search_path = '' as $$
declare v_borrowing public.board_game_borrowings%rowtype;
begin
  update public.board_game_borrowings set status='rejected', rejected_at=now(), approved_by_user_id=p_approver_user_id
  where id=p_borrowing_id and status='pending' returning * into v_borrowing;
  return v_borrowing;
end;
$$;

create function public.cancel_pending_borrowing(p_borrowing_id bigint, p_user_id uuid)
returns public.board_game_borrowings language plpgsql security definer set search_path = '' as $$
declare v_borrowing public.board_game_borrowings%rowtype;
begin
  update public.board_game_borrowings set status='cancelled', cancelled_at=now()
  where id=p_borrowing_id and user_id=p_user_id and status='pending' returning * into v_borrowing;
  return v_borrowing;
end;
$$;

create function public.return_borrowing(p_borrowing_id bigint)
returns public.board_game_borrowings language plpgsql security definer set search_path = ''
as $$
declare v_borrowing public.board_game_borrowings%rowtype; v_board_game public.board_games%rowtype;
begin
  select * into v_borrowing from public.board_game_borrowings where id = p_borrowing_id for update;
  if not found then raise exception using errcode = 'P0001', message = 'BORROWING_NOT_FOUND'; end if;
  if v_borrowing.status <> 'borrowed'::public.borrowing_status then raise exception using errcode = 'P0001', message = 'BORROWING_NOT_BORROWED'; end if;
  select * into v_board_game from public.board_games where id = v_borrowing.board_game_id for update;
  if not found then raise exception using errcode = 'P0001', message = 'BOARD_GAME_NOT_FOUND'; end if;
  if v_board_game.status <> 'borrowed'::public.board_game_status then raise exception using errcode = 'P0001', message = 'BOARD_GAME_STATUS_CONFLICT'; end if;
  update public.board_game_borrowings set status = 'returned'::public.borrowing_status, returned_at = now() where id = v_borrowing.id returning * into v_borrowing;
  update public.board_games set status = 'available'::public.board_game_status where id = v_board_game.id;
  return v_borrowing;
end;
$$;

create function public.set_current_academic_year(p_academic_year_id uuid)
returns public.academic_years language plpgsql security definer set search_path = ''
as $$
declare target_year public.academic_years%rowtype;
begin
  perform pg_catalog.pg_advisory_xact_lock(pg_catalog.hashtext('academic_years:set_current'));
  select * into target_year from public.academic_years where id = p_academic_year_id for update;
  if not found then raise exception using errcode = 'P0001', message = 'ACADEMIC_YEAR_NOT_FOUND'; end if;
  if target_year.is_current then return target_year; end if;
  update public.academic_years set is_current = false where is_current = true;
  update public.academic_years set is_current = true where id = target_year.id returning * into target_year;
  return target_year;
end;
$$;

create function public.update_academic_year(
  p_academic_year_id uuid,
  p_year text,
  p_start_date date,
  p_end_date date
)
returns public.academic_years
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_academic_year public.academic_years%rowtype;
  v_user_id uuid;
begin
  if p_start_date >= p_end_date then
    raise exception using errcode = 'P0001', message = 'ACADEMIC_YEAR_DATE_RANGE_INVALID';
  end if;

  select * into v_academic_year
  from public.academic_years
  where id = p_academic_year_id
  for update;
  if not found then
    raise exception using errcode = 'P0001', message = 'ACADEMIC_YEAR_NOT_FOUND';
  end if;

  if exists (
    select 1 from public.academic_years
    where year = trim(p_year) and id <> p_academic_year_id
  ) then
    raise exception using errcode = 'P0001', message = 'ACADEMIC_YEAR_DUPLICATE';
  end if;

  update public.academic_years
  set year = trim(p_year), start_date = p_start_date, end_date = p_end_date
  where id = p_academic_year_id
  returning * into v_academic_year;

  for v_user_id in
    select distinct affected.user_id
    from (
      select user_id from public.officer_positions where academic_year_id = p_academic_year_id
      union
      select user_id from public.memberships where academic_year_id = p_academic_year_id
    ) as affected
    order by affected.user_id
  loop
    perform pg_catalog.pg_advisory_xact_lock(
      pg_catalog.hashtext('membership_officer:' || v_user_id::text)
    );
    perform public.recompute_membership_types_for_user(v_user_id);
  end loop;

  return v_academic_year;
end;
$$;

create function public.recompute_membership_types_for_user(p_user_id uuid)
returns void language plpgsql security definer set search_path = ''
as $$
begin
  update public.memberships as membership set type = case when exists (
    select 1 from public.officer_positions as officer
    join public.academic_years as officer_year on officer_year.id = officer.academic_year_id
    join public.academic_years as membership_year on membership_year.id = membership.academic_year_id
    where officer.user_id = membership.user_id and officer_year.start_date <= membership_year.start_date
  ) then 'lifetime'::public.merbership_type else 'annual'::public.merbership_type end
  where membership.user_id = p_user_id;
end;
$$;

create function public.create_admin_membership(p_user_id uuid, p_academic_year_id uuid, p_status public.merbership_status, p_joined_at timestamptz)
returns public.memberships language plpgsql security definer set search_path = ''
as $$
declare v_membership public.memberships%rowtype; v_type public.merbership_type;
begin
  if not exists (select 1 from public.users where id = p_user_id) then raise exception using errcode = 'P0001', message = 'MEMBERSHIP_USER_NOT_FOUND'; end if;
  if not exists (select 1 from public.academic_years where id = p_academic_year_id) then raise exception using errcode = 'P0001', message = 'MEMBERSHIP_ACADEMIC_YEAR_NOT_FOUND'; end if;
  perform pg_catalog.pg_advisory_xact_lock(pg_catalog.hashtext('membership_officer:' || p_user_id::text));
  select case when exists (select 1 from public.officer_positions o join public.academic_years oy on oy.id=o.academic_year_id join public.academic_years my on my.id=p_academic_year_id where o.user_id=p_user_id and oy.start_date <= my.start_date) then 'lifetime'::public.merbership_type else 'annual'::public.merbership_type end into v_type;
  insert into public.memberships (user_id,type,academic_year_id,status,joined_at,membership_register_key_id) values (p_user_id,v_type,p_academic_year_id,p_status,coalesce(p_joined_at,now()),null) returning * into v_membership;
  return v_membership;
end;
$$;

create function public.update_admin_membership(p_membership_id uuid, p_academic_year_id uuid, p_status public.merbership_status, p_joined_at timestamptz)
returns public.memberships language plpgsql security definer set search_path = ''
as $$
declare v_membership public.memberships%rowtype;
begin
  select * into v_membership from public.memberships where id = p_membership_id for update;
  if not found then raise exception using errcode = 'P0001', message = 'MEMBERSHIP_NOT_FOUND'; end if;
  if not exists (select 1 from public.academic_years where id = p_academic_year_id) then raise exception using errcode = 'P0001', message = 'MEMBERSHIP_ACADEMIC_YEAR_NOT_FOUND'; end if;
  perform pg_catalog.pg_advisory_xact_lock(pg_catalog.hashtext('membership_officer:' || v_membership.user_id::text));
  update public.memberships set academic_year_id=p_academic_year_id,status=p_status,joined_at=coalesce(p_joined_at,v_membership.joined_at) where id=p_membership_id returning * into v_membership;
  perform public.recompute_membership_types_for_user(v_membership.user_id);
  select * into v_membership from public.memberships where id=p_membership_id;
  return v_membership;
end;
$$;

create function public.create_officer_position(p_user_id uuid, p_academic_year_id uuid, p_title text)
returns public.officer_positions language plpgsql security definer set search_path = ''
as $$
declare v_position public.officer_positions%rowtype;
begin
  if not exists (select 1 from public.users where id=p_user_id) then raise exception using errcode='P0001',message='OFFICER_USER_NOT_FOUND'; end if;
  if not exists (select 1 from public.academic_years where id=p_academic_year_id) then raise exception using errcode='P0001',message='OFFICER_ACADEMIC_YEAR_NOT_FOUND'; end if;
  if nullif(trim(p_title),'') is null then raise exception using errcode='P0001',message='OFFICER_TITLE_REQUIRED'; end if;
  perform pg_catalog.pg_advisory_xact_lock(pg_catalog.hashtext('membership_officer:' || p_user_id::text));
  insert into public.officer_positions(user_id,academic_year_id,title) values(p_user_id,p_academic_year_id,trim(p_title)) returning * into v_position;
  perform public.recompute_membership_types_for_user(p_user_id);
  return v_position;
end;
$$;

create function public.update_officer_position(p_officer_position_id uuid, p_academic_year_id uuid, p_title text)
returns public.officer_positions language plpgsql security definer set search_path = ''
as $$
declare v_position public.officer_positions%rowtype;
begin
  select * into v_position from public.officer_positions where id=p_officer_position_id for update;
  if not found then raise exception using errcode='P0001',message='OFFICER_POSITION_NOT_FOUND'; end if;
  if not exists (select 1 from public.academic_years where id=p_academic_year_id) then raise exception using errcode='P0001',message='OFFICER_ACADEMIC_YEAR_NOT_FOUND'; end if;
  if nullif(trim(p_title),'') is null then raise exception using errcode='P0001',message='OFFICER_TITLE_REQUIRED'; end if;
  perform pg_catalog.pg_advisory_xact_lock(pg_catalog.hashtext('membership_officer:' || v_position.user_id::text));
  update public.officer_positions set academic_year_id=p_academic_year_id,title=trim(p_title) where id=p_officer_position_id returning * into v_position;
  perform public.recompute_membership_types_for_user(v_position.user_id);
  return v_position;
end;
$$;

create function public.delete_officer_position(p_officer_position_id uuid)
returns void language plpgsql security definer set search_path = ''
as $$
declare v_position public.officer_positions%rowtype;
begin
  select * into v_position from public.officer_positions where id=p_officer_position_id for update;
  if not found then raise exception using errcode='P0001',message='OFFICER_POSITION_NOT_FOUND'; end if;
  perform pg_catalog.pg_advisory_xact_lock(pg_catalog.hashtext('membership_officer:' || v_position.user_id::text));
  delete from public.officer_positions where id=p_officer_position_id;
  perform public.recompute_membership_types_for_user(v_position.user_id);
end;
$$;

create trigger update_users_updated_at
before update on public.users
for each row execute function public.update_updated_at_column();

create trigger update_user_profiles_updated_at
before update on public.user_profiles
for each row execute function public.update_updated_at_column();

create trigger update_auth_credentials_updated_at
before update on public.auth_credentials
for each row execute function public.update_updated_at_column();

create trigger update_memberships_updated_at
before update on public.memberships
for each row execute function public.update_updated_at_column();

create trigger update_board_games_updated_at
before update on public.board_games
for each row execute function public.update_updated_at_column();

create trigger update_board_game_reviews_updated_at
before update on public.board_game_reviews
for each row execute function public.update_updated_at_column();

create trigger update_announcements_updated_at
before update on public.announcements
for each row execute function public.update_updated_at_column();

create trigger set_membership_register_keys_updated_at
before update on public.membership_register_keys
for each row execute function public.set_updated_at();

-- Privileged RPCs are callable only by the server-side service-role client.
revoke all privileges on function public.register_user(text, text, text, text, text)
  from public, anon, authenticated;
revoke all privileges on function public.claim_membership_register_key(text, uuid)
  from public, anon, authenticated;
revoke all privileges on function public.generate_membership_register_keys(uuid, integer, text, uuid)
  from public, anon, authenticated;
revoke all privileges on function public.checkout_borrowing(bigint, timestamptz)
  from public, anon, authenticated;
revoke all privileges on function public.return_borrowing(bigint)
  from public, anon, authenticated;
revoke all privileges on function public.approve_borrowing(bigint, uuid) from public, anon, authenticated;
revoke all privileges on function public.reject_borrowing(bigint, uuid) from public, anon, authenticated;
revoke all privileges on function public.cancel_pending_borrowing(bigint, uuid) from public, anon, authenticated;
revoke all privileges on function public.set_current_academic_year(uuid)
  from public, anon, authenticated;
revoke all privileges on function public.update_academic_year(uuid, text, date, date)
  from public, anon, authenticated;
revoke all privileges on function public.recompute_membership_types_for_user(uuid)
  from public, anon, authenticated, service_role;
revoke all privileges on function public.create_admin_membership(uuid, uuid, public.merbership_status, timestamptz)
  from public, anon, authenticated;
revoke all privileges on function public.update_admin_membership(uuid, uuid, public.merbership_status, timestamptz)
  from public, anon, authenticated;
revoke all privileges on function public.create_officer_position(uuid, uuid, text)
  from public, anon, authenticated;
revoke all privileges on function public.update_officer_position(uuid, uuid, text)
  from public, anon, authenticated;
revoke all privileges on function public.delete_officer_position(uuid)
  from public, anon, authenticated;

grant execute on function public.register_user(text, text, text, text, text) to service_role;
revoke all privileges on function public.issue_email_verification_token(uuid, text, timestamptz, timestamptz)
  from public, anon, authenticated;
revoke all privileges on function public.consume_email_verification_token(text)
  from public, anon, authenticated;
grant execute on function public.issue_email_verification_token(uuid, text, timestamptz, timestamptz)
  to service_role;
grant execute on function public.consume_email_verification_token(text)
  to service_role;
revoke all privileges on table public.email_verification_tokens
  from public, anon, authenticated;
grant select, insert, update, delete on table public.email_verification_tokens
  to service_role;
grant execute on function public.claim_membership_register_key(text, uuid) to service_role;
grant execute on function public.generate_membership_register_keys(uuid, integer, text, uuid) to service_role;
grant execute on function public.checkout_borrowing(bigint, timestamptz) to service_role;
grant execute on function public.return_borrowing(bigint) to service_role;
grant execute on function public.approve_borrowing(bigint, uuid) to service_role;
grant execute on function public.reject_borrowing(bigint, uuid) to service_role;
grant execute on function public.cancel_pending_borrowing(bigint, uuid) to service_role;
grant execute on function public.set_current_academic_year(uuid) to service_role;
grant execute on function public.update_academic_year(uuid, text, date, date) to service_role;
grant execute on function public.create_admin_membership(uuid, uuid, public.merbership_status, timestamptz) to service_role;
grant execute on function public.update_admin_membership(uuid, uuid, public.merbership_status, timestamptz) to service_role;
grant execute on function public.create_officer_position(uuid, uuid, text) to service_role;
grant execute on function public.update_officer_position(uuid, uuid, text) to service_role;
grant execute on function public.delete_officer_position(uuid) to service_role;

revoke all privileges on table public.board_games_with_statistics
  from public, anon, authenticated;
grant select on table public.board_games_with_statistics to service_role;

revoke all privileges on table public.board_game_reviews
  from public, anon, authenticated;
grant select, insert, update, delete on table public.board_game_reviews
  to service_role;
revoke all privileges on table public.board_game_review_statistics
  from public, anon, authenticated;
grant select on table public.board_game_review_statistics to service_role;
revoke all privileges on table public.board_game_popularity_statistics
  from public, anon, authenticated;
grant select on table public.board_game_popularity_statistics to service_role;

grant execute on function public.update_updated_at_column()
  to public, anon, authenticated, service_role;
grant execute on function public.set_updated_at()
  to public, anon, authenticated, service_role;

alter table public.academic_years enable row level security;
alter table public.announcements enable row level security;
alter table public.auth_credentials enable row level security;
alter table public.board_game_borrowings enable row level security;
alter table public.board_game_categories enable row level security;
alter table public.board_game_locations enable row level security;
alter table public.board_games enable row level security;
alter table public.board_game_reviews enable row level security;
alter table public.event_attendances enable row level security;
alter table public.events enable row level security;
alter table public.email_verification_tokens enable row level security;
alter table public.membership_register_keys enable row level security;
alter table public.memberships enable row level security;
alter table public.officer_positions enable row level security;
alter table public.sessions enable row level security;
alter table public.user_profiles enable row level security;
alter table public.users enable row level security;

-- The verified remote schema has no public-table RLS policies and does not force RLS.

-- Phase 3G：以下為待部署的 202609140001；不是已套用遠端的聲明。
-- 註銷保留 User FK；closed_at 同時代表停止登入及本次去識別已完成。
-- 不提供復原 RPC，不修改任何既有帳號或社團歷史。
alter table public.users add column closed_at timestamptz;
alter table public.users add constraint users_closed_identity_check check (
  closed_at is null or (
    name = '已註銷使用者' and avatar is null and email_verified_at is null
    and email ~ '^closed-[0-9a-f-]{36}@account\.invalid$'
  )
);

-- 所有新認證資料／開放借用共用 User row lock，避免註銷檢查與新增並行。
create function public.require_open_account() returns trigger
language plpgsql security definer set search_path = '' as $$
declare v_closed_at timestamptz;
begin
  if new.user_id is null then return new; end if;
  select closed_at into v_closed_at from public.users where id = new.user_id for update;
  if not found or v_closed_at is not null then
    raise exception using errcode = 'PCL01', message = 'ACCOUNT_CLOSED';
  end if;
  return new;
end;
$$;

create trigger sessions_require_open_account before insert or update of user_id on public.sessions
for each row execute function public.require_open_account();
create trigger credentials_require_open_account before insert or update of user_id on public.auth_credentials
for each row execute function public.require_open_account();
create trigger profiles_require_open_account before insert or update of user_id on public.user_profiles
for each row execute function public.require_open_account();
create trigger verification_require_open_account before insert or update of user_id on public.email_verification_tokens
for each row execute function public.require_open_account();
create trigger borrowings_require_open_account before insert or update of user_id, status on public.board_game_borrowings
for each row when (new.status in ('pending', 'approved', 'borrowed'))
execute function public.require_open_account();

-- 已註銷帳號不可經一般帳號更新／驗證流程重新寫入個資或復原。
create function public.protect_closed_account() returns trigger
language plpgsql security definer set search_path = '' as $$
begin
  if old.closed_at is not null and new is distinct from old then
    raise exception using errcode = 'PCL01', message = 'ACCOUNT_CLOSED';
  end if;
  return new;
end;
$$;
create trigger users_protect_closed_account before update on public.users
for each row execute function public.protect_closed_account();

/**
 * 僅供受信任 Server 呼叫：由 cookie token 解析目標，不接受指定 User ID。
 * Server 先驗證目前密碼；交易內再核對當時比較的 hash，防止重驗期間密碼已改。
 * User lock 後重新核對 Session、借用及憑證；任一步失敗即整筆 rollback。
 */
create function public.close_account(p_session_token text, p_expected_password_hash text)
returns void language plpgsql security definer set search_path = '' as $$
declare v_user_id uuid; v_closed_at timestamptz; v_hash text;
begin
  select user_id into v_user_id from public.sessions
    where token = p_session_token and expires_at > clock_timestamp();
  if not found then
    raise exception using errcode = 'PCL01', message = 'INVALID_SESSION';
  end if;
  select closed_at into v_closed_at from public.users where id = v_user_id for update;
  if not found or v_closed_at is not null then
    raise exception using errcode = 'PCL01', message = 'ACCOUNT_CLOSED';
  end if;
  perform 1 from public.sessions where token = p_session_token and user_id = v_user_id
    and expires_at > clock_timestamp() for update;
  if not found then
    raise exception using errcode = 'PCL01', message = 'INVALID_SESSION';
  end if;
  select password_hash into v_hash from public.auth_credentials where user_id = v_user_id for update;
  if not found or p_expected_password_hash is null or v_hash <> p_expected_password_hash then
    raise exception using errcode = 'PCL03', message = 'REAUTH_REQUIRED';
  end if;
  if exists (select 1 from public.board_game_borrowings where user_id = v_user_id
    and status in ('pending', 'approved', 'borrowed')) then
    raise exception using errcode = 'PCL02', message = 'OPEN_BORROWINGS';
  end if;

  delete from public.email_verification_tokens where user_id = v_user_id;
  delete from public.sessions where user_id = v_user_id;
  delete from public.auth_credentials where user_id = v_user_id;
  delete from public.user_profiles where user_id = v_user_id;
  update public.users set name = '已註銷使用者',
    email = 'closed-' || gen_random_uuid()::text || '@account.invalid',
    avatar = null, email_verified_at = null, closed_at = clock_timestamp(), updated_at = clock_timestamp()
    where id = v_user_id;
end;
$$;

revoke all on function public.require_open_account() from public, anon, authenticated;
revoke all on function public.protect_closed_account() from public, anon, authenticated;
revoke all on function public.close_account(text, text) from public, anon, authenticated;
grant execute on function public.close_account(text, text) to service_role;

-- Phase 3K-S1 相容階段目標結構；舊 token 欄位留待 Stage D 清除。
-- Stage A：新增雜湊欄位，不回填、不清除 Session，並保留舊 RPC。
-- token 允許 NULL，讓新應用只保存雜湊；舊應用仍可使用 legacy row。
alter table public.sessions add column token_hash text;
alter table public.sessions alter column token drop not null;
alter table public.sessions add constraint sessions_credential_state_check check (
  (token is not null and token_hash is null) or
  (token is null and token_hash is not null and token_hash ~ '^[0-9a-f]{64}$')
);
create unique index sessions_token_hash_key on public.sessions(token_hash) where token_hash is not null;

-- 使用獨立函式名稱維持舊應用相容性；保留 Phase 3G 的鎖定與原子註銷契約。
create function public.close_account_by_session_hash(p_session_token_hash text, p_expected_password_hash text)
returns void language plpgsql security definer set search_path = '' as $$
declare v_user_id uuid; v_closed_at timestamptz; v_hash text;
begin
  select user_id into v_user_id from public.sessions
    where token_hash = p_session_token_hash and expires_at > clock_timestamp();
  if not found then
    raise exception using errcode = 'PCL01', message = 'INVALID_SESSION';
  end if;
  select closed_at into v_closed_at from public.users where id = v_user_id for update;
  if not found or v_closed_at is not null then
    raise exception using errcode = 'PCL01', message = 'ACCOUNT_CLOSED';
  end if;
  perform 1 from public.sessions where token_hash = p_session_token_hash and user_id = v_user_id
    and expires_at > clock_timestamp() for update;
  if not found then
    raise exception using errcode = 'PCL01', message = 'INVALID_SESSION';
  end if;
  select password_hash into v_hash from public.auth_credentials where user_id = v_user_id for update;
  if not found or p_expected_password_hash is null or v_hash <> p_expected_password_hash then
    raise exception using errcode = 'PCL03', message = 'REAUTH_REQUIRED';
  end if;
  if exists (select 1 from public.board_game_borrowings where user_id = v_user_id
    and status in ('pending', 'approved', 'borrowed')) then
    raise exception using errcode = 'PCL02', message = 'OPEN_BORROWINGS';
  end if;

  delete from public.email_verification_tokens where user_id = v_user_id;
  delete from public.sessions where user_id = v_user_id;
  delete from public.auth_credentials where user_id = v_user_id;
  delete from public.user_profiles where user_id = v_user_id;
  update public.users set name = '已註銷使用者',
    email = 'closed-' || gen_random_uuid()::text || '@account.invalid',
    avatar = null, email_verified_at = null, closed_at = clock_timestamp(), updated_at = clock_timestamp()
    where id = v_user_id;
end;
$$;


revoke all on function public.close_account_by_session_hash(text,text) from public, anon, authenticated;
grant execute on function public.close_account_by_session_hash(text,text) to service_role;
