export class BoardNotFoundError extends Error { constructor() { super("找不到此桌遊。"); this.name = "BoardNotFoundError"; } }
export class DuplicateInventoryNumberError extends Error { constructor() { super("此社產編號已被使用。"); this.name = "DuplicateInventoryNumberError"; } }
export class BorrowingNotFoundError extends Error { constructor() { super("找不到此借用紀錄。"); this.name = "BorrowingNotFoundError"; } }
export class BoardGameCategoryNotFoundError extends Error { constructor() { super("找不到此桌遊種類。"); this.name = "BoardGameCategoryNotFoundError"; } }
export class DuplicateBoardGameCategoryNameError extends Error { constructor() { super("桌遊種類名稱已存在。"); this.name = "DuplicateBoardGameCategoryNameError"; } }
export class BoardGameCategoryInUseError extends Error { constructor() { super("此桌遊種類仍被社產使用，無法刪除。"); this.name = "BoardGameCategoryInUseError"; } }
export class BoardGameLocationNotFoundError extends Error { constructor() { super("找不到此桌遊位置。"); this.name = "BoardGameLocationNotFoundError"; } }
export class DuplicateBoardGameLocationNameError extends Error { constructor() { super("桌遊位置名稱已存在。"); this.name = "DuplicateBoardGameLocationNameError"; } }
export class BoardGameLocationInUseError extends Error { constructor() { super("此桌遊位置仍被社產使用，無法刪除。"); this.name = "BoardGameLocationInUseError"; } }
export class BoardGameHasOpenBorrowingError extends Error { constructor() { super("此桌遊仍有未結束的借用流程，無法執行此操作。"); this.name = "BoardGameHasOpenBorrowingError"; } }
export class BoardGameNotAvailableForBorrowingError extends Error { constructor() { super("此桌遊目前不可借用。"); this.name = "BoardGameNotAvailableForBorrowingError"; } }
export class BoardGameBorrowingConflictError extends Error { constructor() { super("您已對此桌遊提出尚未結束的借用申請。"); this.name = "BoardGameBorrowingConflictError"; } }
export class BorrowingDueDateError extends Error { constructor() { super("應還時間必須是未來的有效日期。"); this.name = "BorrowingDueDateError"; } }
export class BorrowingCancellationConflictError extends Error { constructor() { super("這筆借用申請目前已無法取消，請重新整理後確認最新狀態。"); this.name = "BorrowingCancellationConflictError"; } }
export class BorrowingStatusTransitionError extends Error { constructor(expectedStatus: string, actualStatus: string) { super(`此操作需要「${expectedStatus}」狀態，目前為「${actualStatus}」。`); this.name = "BorrowingStatusTransitionError"; } }
export class BorrowingWorkflowConflictError extends Error { constructor(message: string) { super(message); this.name = "BorrowingWorkflowConflictError"; } }
