import { NextResponse } from "next/server";
import { ZodError, z } from "zod";
import { authorizeAdminRequest } from "@/libs/api/admin-authorization";
import { boardGamesService } from "@/services/board-games/board-games.service";
import { boardGameMasterDataSchema } from "@/services/board-games/board-games.schema";
import { BoardGameCategoryInUseError, BoardGameCategoryNotFoundError, DuplicateBoardGameCategoryNameError } from "@/services/board-games/board-games.errors";
import { unexpectedErrorResponse } from "@/libs/api/server-response";
type Context = { params: Promise<{ id: string }> };
export async function PATCH(request: Request, { params }: Context) { const authorization = await authorizeAdminRequest("您沒有管理桌遊種類的權限"); if (authorization.response) return authorization.response; try { return NextResponse.json({ data: await boardGamesService.updateCategory((await params).id, boardGameMasterDataSchema.parse(await request.json())) }); } catch (error) { if (error instanceof ZodError) return NextResponse.json({ message: "輸入資料格式不正確", errors: z.treeifyError(error) }, { status: 400 }); if (error instanceof BoardGameCategoryNotFoundError) return NextResponse.json({ message: error.message }, { status: 404 }); if (error instanceof DuplicateBoardGameCategoryNameError) return NextResponse.json({ message: error.message }, { status: 409 }); return unexpectedErrorResponse("[PATCH /api/admin/board-game-categories/[id]]", error, "更新桌遊種類失敗，請稍後再試"); } }
export async function DELETE(_: Request, { params }: Context) { const authorization = await authorizeAdminRequest("您沒有管理桌遊種類的權限"); if (authorization.response) return authorization.response; try { await boardGamesService.deleteCategory((await params).id); return NextResponse.json({ data: null }); } catch (error) { if (error instanceof BoardGameCategoryNotFoundError) return NextResponse.json({ message: error.message }, { status: 404 }); if (error instanceof BoardGameCategoryInUseError) return NextResponse.json({ message: error.message }, { status: 409 }); return unexpectedErrorResponse("[DELETE /api/admin/board-game-categories/[id]]", error, "刪除桌遊種類失敗，請稍後再試"); } }
