-- Historical initial schema reconstructed from the earliest canonical snapshot,
-- pre-202608230001 application types/repositories, and later migration deltas.
-- This migration contains only objects that existed before 202608230001.

-- pgcrypto is required by gen_random_uuid() and later migrations.
create schema if not exists extensions;
create extension if not exists pgcrypto with schema extensions;

-- Remote extension inventory also contained uuid-ossp, pg_stat_statements,
-- supabase_vault, and the built-in plpgsql language. They are not referenced by
-- the public application objects below. Enable platform-managed extensions in
-- the target Supabase project only when that environment requires them.

create type public.attendance_status as enum ('present', 'absent', 'late');
create type public.board_game_status as enum (
  'available',
  'borrowed',
  'maintenance',
  'lost',
  'damaged',
  'retired'
);
create type public.borrowing_status as enum (
  'pending',
  'approved',
  'rejected',
  'borrowed',
  'returned'
);
-- These names match the verified remote schema. Do not correct the spelling in
-- a snapshot or migration without a separately approved compatibility plan.
create type public.merbership_status as enum (
  'pending',
  'active',
  'expired',
  'suspended',
  'cancelled'
);
create type public.merbership_type as enum ('annual', 'lifetime');

create table public.users (
  id uuid constraint users_pkey primary key default gen_random_uuid(),
  created_at timestamptz not null default now(),
  name text not null,
  email text not null,
  avatar text,
  updated_at timestamptz not null default now(),
  constraint users_email_key unique (email)
);

create table public.academic_years (
  id uuid constraint academic_years_pkey primary key default gen_random_uuid(),
  start_date timestamptz not null,
  end_date timestamptz not null,
  year text not null,
  is_current boolean not null,
  constraint academic_years_year_key unique (year)
);

create table public.board_game_categories (
  id uuid constraint board_game_category_pkey primary key default gen_random_uuid(),
  name text not null,
  description text
);

create table public.board_game_locations (
  id uuid constraint locations_pkey primary key default gen_random_uuid(),
  name text not null,
  description text
);

create table public.events (
  id uuid constraint events_pkey primary key default gen_random_uuid(),
  created_at timestamptz not null default now(),
  start_time timestamptz not null,
  end_time timestamptz not null,
  name text not null,
  description text
);

create table public.user_profiles (
  id bigint generated by default as identity constraint user_profiles_pkey primary key,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  grade text,
  phone text not null,
  school text,
  department text,
  real_name text not null,
  user_id uuid not null,
  student_id text,
  constraint user_profiles_user_id_fkey
    foreign key (user_id) references public.users(id)
    on delete no action on update no action,
  constraint user_profiles_user_id_key unique (user_id)
);

create table public.auth_credentials (
  id uuid constraint auth_credentials_pkey primary key default gen_random_uuid(),
  created_at timestamptz not null default now(),
  password_hash text not null,
  updated_at timestamptz not null default now(),
  user_id uuid not null,
  constraint auth_credentials_user_id_fkey
    foreign key (user_id) references public.users(id)
    on delete no action on update no action
);

create table public.sessions (
  id uuid constraint seessions_pkey primary key default gen_random_uuid(),
  created_at timestamptz not null default now(),
  token text not null,
  expires_at timestamptz not null,
  last_accessed_at timestamptz not null default now(),
  user_id uuid not null,
  constraint seessions_token_key unique (token),
  constraint sessions_user_id_fkey
    foreign key (user_id) references public.users(id)
    on delete no action on update no action
);

create table public.officer_positions (
  id uuid constraint positions_pkey primary key default gen_random_uuid(),
  title text not null,
  created_at timestamptz not null default now(),
  academic_year_id uuid not null,
  user_id uuid not null,
  constraint officer_positions_academic_year_id_fkey
    foreign key (academic_year_id) references public.academic_years(id)
    on delete no action on update no action,
  constraint officer_positions_user_id_fkey
    foreign key (user_id) references public.users(id)
    on delete no action on update no action
);

create table public.board_games (
  id uuid constraint board_games_pkey primary key default gen_random_uuid(),
  created_at timestamptz not null default now(),
  name text not null,
  description text,
  image text,
  updated_at timestamptz not null default now(),
  category_id uuid not null default gen_random_uuid(),
  location_id uuid not null default gen_random_uuid(),
  status public.board_game_status not null,
  inventory_number bigint not null,
  constraint board_games_category_id_fkey
    foreign key (category_id) references public.board_game_categories(id)
    on delete no action on update no action,
  constraint board_games_location_id_fkey
    foreign key (location_id) references public.board_game_locations(id)
    on delete no action on update no action,
  constraint board_games_inventory_number_key unique (inventory_number)
);

create table public.memberships (
  id uuid constraint merberships_pkey primary key default gen_random_uuid(),
  created_at timestamptz not null default now(),
  type public.merbership_type not null,
  status public.merbership_status not null,
  updated_at timestamptz not null default now(),
  joined_at timestamptz not null,
  academic_year_id uuid not null,
  user_id uuid not null,
  register_key text not null,
  constraint merberships_academic_year_id_fkey
    foreign key (academic_year_id) references public.academic_years(id)
    on delete no action on update no action,
  constraint merberships_user_id_fkey
    foreign key (user_id) references public.users(id)
    on delete no action on update no action
);

create table public.board_game_borrowings (
  id bigint generated by default as identity constraint board_game_borrowings_pkey primary key,
  created_at timestamptz not null default now(),
  borrowed_at timestamptz,
  due_at timestamptz,
  returned_at timestamptz,
  status public.borrowing_status not null,
  approved_by_user_id uuid,
  user_id uuid not null,
  board_game_id uuid not null,
  constraint board_game_borrowings_approved_by_user_id_fkey
    foreign key (approved_by_user_id) references public.users(id)
    on delete no action on update no action,
  constraint board_game_borrowings_user_id_fkey
    foreign key (user_id) references public.users(id)
    on delete no action on update no action,
  constraint board_game_borrowings_board_game_id_fkey
    foreign key (board_game_id) references public.board_games(id)
    on delete no action on update no action
);

create table public.event_attendances (
  id bigint generated by default as identity constraint event_attendances_pkey primary key,
  attended_at timestamptz,
  status public.attendance_status not null,
  user_id uuid not null,
  event_id uuid not null,
  constraint event_attendances_user_id_fkey
    foreign key (user_id) references public.users(id)
    on delete no action on update no action,
  constraint event_attendances_event_id_fkey
    foreign key (event_id) references public.events(id)
    on delete no action on update no action
);

create table public.announcements (
  id bigint generated by default as identity constraint announcements_pkey primary key,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  title text not null,
  content text not null,
  is_published boolean not null,
  published_at timestamptz,
  author_id uuid not null,
  constraint announcements_author_id_fkey
    foreign key (author_id) references public.users(id)
    on delete no action on update no action
);

create or replace function public.register_user(
  p_email text,
  p_name text,
  p_password_hash text
)
returns public.users
language plpgsql
security definer
as $$
declare
  new_user public.users;
begin
  insert into public.users (email, name)
  values (p_email, p_name)
  returning * into new_user;

  insert into public.auth_credentials (user_id, password_hash)
  values (new_user.id, p_password_hash);

  return new_user;
end;
$$;

create or replace function public.update_updated_at_column()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create trigger update_users_updated_at
before update on public.users
for each row execute function public.update_updated_at_column();

create trigger update_user_profiles_updated_at
before update on public.user_profiles
for each row execute function public.update_updated_at_column();

create trigger update_auth_credentials_updated_at
before update on public.auth_credentials
for each row execute function public.update_updated_at_column();

create trigger update_memberships_updated_at
before update on public.memberships
for each row execute function public.update_updated_at_column();

create trigger update_board_games_updated_at
before update on public.board_games
for each row execute function public.update_updated_at_column();

create trigger update_announcements_updated_at
before update on public.announcements
for each row execute function public.update_updated_at_column();

-- Verified remote ACLs are intentionally preserved. They are documented here as
-- current state, not as a security recommendation or hardening change.
grant execute on function public.register_user(text, text, text)
  to public, anon, authenticated, service_role;
grant execute on function public.update_updated_at_column()
  to public, anon, authenticated, service_role;
alter table public.academic_years enable row level security;
alter table public.announcements enable row level security;
alter table public.auth_credentials enable row level security;
alter table public.board_game_borrowings enable row level security;
alter table public.board_game_categories enable row level security;
alter table public.board_game_locations enable row level security;
alter table public.board_games enable row level security;
alter table public.event_attendances enable row level security;
alter table public.events enable row level security;
alter table public.memberships enable row level security;
alter table public.officer_positions enable row level security;
alter table public.sessions enable row level security;
alter table public.user_profiles enable row level security;
alter table public.users enable row level security;

-- The verified remote schema has no public-table RLS policies and does not force RLS.
